# Generated by Django 6.0.4 on 2026-06-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_comments_datetime_created_comments_datetime_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
