# Generated by Django 6.0.4 on 2026-07-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.CharField(default='p', max_length=1, verbose_name='وضعیت کامنت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='hide_name',
            field=models.BooleanField(default=True, verbose_name='نمایش نام کاربری'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.blogpost', verbose_name='پست مربوطه'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='province',
            field=models.CharField(blank=True, choices=[('kh razavi', 'خراسان رضوی'), ('Tehran', 'تهران'), ('Esfehan', 'اصفهان')], max_length=255, verbose_name='استان'),
        ),
    ]
