# Generated by Django 6.0.4 on 2026-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_comment_state_alter_comment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='state',
            field=models.CharField(choices=[('a', 'تایید شده'), ('r', 'رد شده'), ('p', 'در حال بررسی')], default='p', max_length=1, verbose_name='وضعیت کامنت'),
        ),
    ]
