# Generated by Django 6.0.4 on 2026-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0010_alter_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
    ]
